/// Measures - Central location for all DAX measures
/// Keep all measures organized here instead of scattering across tables
table Measures
	lineageTag: 00000000-0000-0000-0000-000000000101

	/// Total Sales - Sum of all sales amount
	/// Owner: BI Team
	measure 'Total Sales' = SUM(Sample_Data[Amount])
		formatString: #,##0
		lineageTag: 00000000-0000-0000-0000-000000000102

	/// TODO: Add your measures here following the pattern above
	/// Each measure should have a description comment

	partition Measures = m
		mode: import
		source =
			let
			    Source = #table({"Placeholder"}, {{""}})
			in
			    Source

	annotation PBI_ResultType = Table
