table 'ADJUNCTS SUPPLIER DETAILS'
	lineageTag: c1d42366-79ee-4f30-9715-768651127e0f

	column 'Supplier Name'
		dataType: string
		lineageTag: 0eddf302-fce3-41b6-99c3-8078916baca8
		summarizeBy: none
		sourceColumn: Supplier Name

		annotation SummarizationSetBy = Automatic

	column 'Update supplier name'
		dataType: string
		lineageTag: 080d4d3c-df97-45f0-9b56-ca2d8ff96346
		summarizeBy: none
		sourceColumn: Update supplier name

		annotation SummarizationSetBy = Automatic

	column 'VOP/3rd Party'
		dataType: string
		lineageTag: f3d992da-923a-4d12-8009-7b324a1ac80b
		summarizeBy: none
		sourceColumn: VOP/3rd Party

		annotation SummarizationSetBy = Automatic

	column 'Master Supplier '
		dataType: string
		lineageTag: 7414be8d-1150-47bd-b0da-d6445ef6cf83
		summarizeBy: none
		sourceColumn: "Master Supplier "

		annotation SummarizationSetBy = Automatic

	column 'Update master supplier'
		dataType: string
		lineageTag: b997bf3a-932f-4267-88ca-a19b822fe7b1
		summarizeBy: none
		sourceColumn: Update master supplier

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 8b1d97f7-1c0c-41ec-a163-e2d5c27b8fa3
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	partition 'ADJUNCTS SUPPLIER DETAILS' = m
		mode: import
		queryGroup: 'Trend Analysis'
		source =
				let
				    Source = SharePoint.Files("https://anheuserbuschinbev.sharepoint.com/sites/Sustinability/", [ApiVersion = 15]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Name] = "Adjuncts supplier details.xlsx")),
				    #"Filtered Hidden Files1" = Table.SelectRows(#"Filtered Rows", each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (2)", each #"Transform File (2)"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File (2)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (2)", Table.ColumnNames(#"Transform File (2)"(#"Sample File (2)"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"", type text}, {"Name", type text}, {"Update supplier name", type any}, {"VOP/3rd Party", type text}, {"Parent", type text}, {"Update master supplier", type any}, {"Delete Adjunct supplier?", type logical}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Source.Name", "", "Delete Adjunct supplier?"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Name", "Supplier Name"}, {"Parent", "Master Supplier Name"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Segment", each "Adjucnts"),
				    #"Renamed Columns2" = Table.RenameColumns(#"Added Custom",{{"Master Supplier Name", "Master Supplier "}})
				in
				    #"Renamed Columns2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

