table 'PACK SUPPLIER DETAILS'
	lineageTag: d62e44f5-d364-4f47-a028-036cb869df15

	column 'Supplier Name'
		dataType: string
		lineageTag: 0d501c15-35f6-4e82-9bf7-16ac20d9e796
		summarizeBy: none
		sourceColumn: Supplier Name

		annotation SummarizationSetBy = Automatic

	column 'Update supplier name'
		dataType: string
		lineageTag: c193ba97-e26e-4847-8d78-09893e06dfcb
		summarizeBy: none
		sourceColumn: Update supplier name

		annotation SummarizationSetBy = Automatic

	column 'Master Supplier'
		dataType: string
		lineageTag: 67f3147f-25a8-41cc-8297-8f0e72ef3dd8
		summarizeBy: none
		sourceColumn: Master Supplier

		annotation SummarizationSetBy = Automatic

	column 'Update master supplier'
		dataType: string
		lineageTag: 699640de-6fad-4c42-b051-ce57108e8749
		summarizeBy: none
		sourceColumn: Update master supplier

		annotation SummarizationSetBy = Automatic

	column 'VOP/3rd Party'
		dataType: string
		lineageTag: 00bcd572-2144-4aa4-889a-f30dd2b2794d
		summarizeBy: none
		sourceColumn: VOP/3rd Party

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 330efbe9-5b3b-42ab-9403-d8bfff5f3b34
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	partition 'PACK SUPPLIER DETAILS' = m
		mode: import
		queryGroup: 'Trend Analysis'
		source =
				let
				    Source = SharePoint.Files("https://anheuserbuschinbev.sharepoint.com/sites/Sustinability/", [ApiVersion = 15]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Name] = "Packaging supplier details.xlsx")),
				    #"Filtered Hidden Files1" = Table.SelectRows(#"Filtered Rows", each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (3)", each #"Transform File (3)"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File (3)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (3)", Table.ColumnNames(#"Transform File (3)"(#"Sample File (3)"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"", type text}, {"Name", type text}, {"Update supplier name", type any}, {"Master supplier", type text}, {"Update master supplier", type any}, {"VOP/3rd Party", type text}, {"Delete supplier?", type logical}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Source.Name", "", "Delete supplier?"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Name", "Supplier Name"}, {"Master supplier", "Master Supplier"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Custom", each "Packaging"),
				    #"Renamed Columns2" = Table.RenameColumns(#"Added Custom",{{"Custom", "Segment"}})
				in
				    #"Renamed Columns2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

